# Recommendation System Notebook
- User based recommendation
- User based prediction & evaluation
- Item based recommendation
- Item based prediction & evaluation

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.activity.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fexperimentsandconfigs%20https%3a%2f%2fwww.googleapis.com%2fauth%2fphotos.native&response_type=code

Enter your authorization code:
4/1AY0e-g47pp6SdhDBO0h0ydOsp_6TY6Vv_afCtAPuCKwPXoATlURSmL5InY0
Mounted at /content/drive


Different Approaches to develop Recommendation System -

1. Demographich based Recommendation System

2. Content Based Recommendation System

3. Collaborative filtering Recommendation System

In [139]:
# import libraties
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sys
import pickle
import re

In [3]:
# Reading ratings file from GitHub. # MovieLens
ratings = pd.read_csv('https://raw.githubusercontent.com/antrikshsaxena/NLPCapstone/main/ratings_final.csv' , encoding='latin-1')
ratings.head()

userId  movieId  rating   timestamp
0       1      296     5.0  1147880044
1       1      306     3.5  1147868817
2       1      307     5.0  1147868828
3       1      665     5.0  1147878820
4       1      899     3.5  1147868510

In [4]:
sys.path.append('/content/drive/MyDrive/Capstone/Product Recommender system')

In [5]:
df = pd.read_csv('/content/drive/MyDrive/Capstone/Product Recommender system/sample30.csv')

In [6]:
df

id            brand  ... reviews_username user_sentiment
0      AV13O1A8GV-KLJ3akUyj  Universal Music  ...           joshua       Positive
1      AV14LG0R-jtxr-f38QfS         Lundberg  ...        dorothy w       Positive
2      AV14LG0R-jtxr-f38QfS         Lundberg  ...        dorothy w       Positive
3      AV16khLE-jtxr-f38VFn              K-Y  ...          rebecca       Negative
4      AV16khLE-jtxr-f38VFn              K-Y  ...        walker557       Negative
...                     ...              ...  ...              ...            ...
29995  AVpfW8y_LJeJML437ySW    L'oreal Paris  ...       laurasnchz       Positive
29996  AVpfW8y_LJeJML437ySW    L'oreal Paris  ...    scarlepadilla       Positive
29997  AVpfW8y_LJeJML437ySW    L'oreal Paris  ...       liviasuexo       Positive
29998  AVpfW8y_LJeJML437ySW    L'oreal Paris  ...         ktreed95       Positive
29999  AVpfW8y_LJeJML437ySW    L'oreal Paris  ...        kcoopxoxo       Positive

[30000 rows x 15 columns]

In [7]:
col = ['name','reviews_rating','reviews_username']

In [8]:
df_master = df[col]

In [9]:
df_master

name  ...  reviews_username
0              Pink Friday: Roman Reloaded Re-Up (w/dvd)  ...            joshua
1             Lundberg Organic Cinnamon Toast Rice Cakes  ...         dorothy w
2             Lundberg Organic Cinnamon Toast Rice Cakes  ...         dorothy w
3                       K-Y Love Sensuality Pleasure Gel  ...           rebecca
4                       K-Y Love Sensuality Pleasure Gel  ...         walker557
...                                                  ...  ...               ...
29995  L'or233al Paris Elvive Extraordinary Clay Reba...  ...        laurasnchz
29996  L'or233al Paris Elvive Extraordinary Clay Reba...  ...     scarlepadilla
29997  L'or233al Paris Elvive Extraordinary Clay Reba...  ...        liviasuexo
29998  L'or233al Paris Elvive Extraordinary Clay Reba...  ...          ktreed95
29999  L'or233al Paris Elvive Extraordinary Clay Reba...  ...         kcoopxoxo

[30000 rows x 3 columns]

In [10]:
df_master.groupby(by=["reviews_username","name"]).mean()

reviews_rating
reviews_username name                                                              
00dog3           Chex Muddy Buddies Brownie Supreme Snack Mix                   4.0
00sab00          Mike Dave Need Wedding Dates (dvd + Digital)                   1.0
                 My Big Fat Greek Wedding 2 (blu-Ray + Dvd + Dig...             3.0
01impala         Godzilla 3d Includes Digital Copy Ultraviolet 3...             3.0
02dakota         Godzilla 3d Includes Digital Copy Ultraviolet 3...             5.0
...                                                                             ...
zxcsdfd          Clorox Disinfecting Wipes Value Pack Scented 15...             5.0
zxjki            Clorox Disinfecting Wipes Value Pack Scented 15...             2.0
zyiah4           Clorox Disinfecting Wipes Value Pack Scented 15...             5.0
zzdiane          My Big Fat Greek Wedding 2 (blu-Ray + Dvd + Dig...             5.0
zzz1127          Clorox Disinfecting Wipes Value Pack Scented 15...             4.0

[27588 rows x 1 columns]

In [11]:
df_master =  df_master.groupby(by=["reviews_username","name"]).mean().reset_index()

In [12]:
df_master.shape

(27588, 3)

## Dividing the dataset into train and test

In [13]:
# Test and Train split of the dataset.
from sklearn.model_selection import train_test_split
train, test = train_test_split(df_master, test_size=0.30, random_state=31)

In [14]:
print(train.shape)
print(test.shape)

(19311, 3)
(8277, 3)


In [15]:
train['reviews_username'].nunique()

17868

In [16]:
df_pivot = train.pivot(
    index='reviews_username',
    columns='name',
    values='reviews_rating'
).fillna(0)

df_pivot.head(3)

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  ...  Yes To Grapefruit Rejuvenating Body Wash
reviews_username                                                                 ...                                          
00dog3                                                          0.0              ...                                       0.0
00sab00                                                         0.0              ...                                       0.0
01impala                                                        0.0              ...                                       0.0

[3 rows x 256 columns]

In [17]:
df_pivot.shape

(17868, 256)

### Creating dummy train & dummy test dataset
These dataset will be used for prediction 
- Dummy train will be used later for prediction of the movies which has not been rated by the user. To ignore the movies rated by the user, we will mark it as 0 during prediction. The movies not rated by user is marked as 1 for prediction in dummy train dataset. 

- Dummy test will be used for evaluation. To evaluate, we will only make prediction on the movies rated by the user. So, this is marked as 1. This is just opposite of dummy_train.

In [18]:
# Copy the train dataset into dummy_train
dummy_train = train.copy()

In [19]:
dummy_train.head()

reviews_username  ... reviews_rating
23966      southern123  ...            5.0
20176        pamelarei  ...            5.0
4296            bzmama  ...            5.0
9913        haliesmith  ...            5.0
12553        jokers709  ...            5.0

[5 rows x 3 columns]

In [20]:
# The movies not rated by user is marked as 1 for prediction. 
dummy_train['reviews_rating'] = dummy_train['reviews_rating'].apply(lambda x: 0 if x>=1 else 1)

In [21]:
# Convert the dummy train dataset into matrix format.
dummy_train = dummy_train.pivot(
    index='reviews_username',
    columns='name',
    values='reviews_rating'
).fillna(1)

In [22]:
dummy_train.head()

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  ...  Yes To Grapefruit Rejuvenating Body Wash
reviews_username                                                                 ...                                          
00dog3                                                          1.0              ...                                       1.0
00sab00                                                         1.0              ...                                       1.0
01impala                                                        1.0              ...                                       1.0
02dakota                                                        1.0              ...                                       1.0
02deuce                                                         1.0              ...                                       1.0

[5 rows x 256 columns]

**Cosine Similarity**

Cosine Similarity is a measurement that quantifies the similarity between two vectors [Which is Rating Vector in this case] 

**Adjusted Cosine**

Adjusted cosine similarity is a modified version of vector-based similarity where we incorporate the fact that different users have different ratings schemes. In other words, some users might rate items highly in general, and others might give items lower ratings as a preference. To handle this nature from rating given by user , we subtract average ratings for each user from each user's rating for different movies.



# User Similarity Matrix

## Using Cosine Similarity

In [23]:
df_pivot.index.nunique()

17868

In [24]:
from sklearn.metrics.pairwise import pairwise_distances

# Creating the User Similarity Matrix using pairwise_distance function.
user_correlation = 1 - pairwise_distances(df_pivot, metric='cosine')
user_correlation[np.isnan(user_correlation)] = 0
print(user_correlation)

[[1.        0.        0.        ... 0.        0.        0.       ]
 [0.        1.        0.        ... 0.        0.9486833 0.       ]
 [0.        0.        1.        ... 0.        0.        0.       ]
 ...
 [0.        0.        0.        ... 1.        0.        1.       ]
 [0.        0.9486833 0.        ... 0.        1.        0.       ]
 [0.        0.        0.        ... 1.        0.        1.       ]]


In [25]:
user_correlation.shape

(17868, 17868)

## Using adjusted Cosine 

### Here, we are not removing the NaN values and calculating the mean only for the movies rated by the user

In [26]:
# Create a user-movie matrix.
df_pivot = train.pivot(
    index='reviews_username',
    columns='name',
    values='reviews_rating'
)

In [27]:
df_pivot.head()

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  ...  Yes To Grapefruit Rejuvenating Body Wash
reviews_username                                                                 ...                                          
00dog3                                                          NaN              ...                                       NaN
00sab00                                                         NaN              ...                                       NaN
01impala                                                        NaN              ...                                       NaN
02dakota                                                        NaN              ...                                       NaN
02deuce                                                         NaN              ...                                       NaN

[5 rows x 256 columns]

### Normalising the rating of the movie for each user around 0 mean

In [28]:
mean = np.nanmean(df_pivot, axis=1)
df_subtracted = (df_pivot.T-mean).T

In [29]:
df_subtracted.head()

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  ...  Yes To Grapefruit Rejuvenating Body Wash
reviews_username                                                                 ...                                          
00dog3                                                          NaN              ...                                       NaN
00sab00                                                         NaN              ...                                       NaN
01impala                                                        NaN              ...                                       NaN
02dakota                                                        NaN              ...                                       NaN
02deuce                                                         NaN              ...                                       NaN

[5 rows x 256 columns]

### Finding cosine similarity

In [30]:
from sklearn.metrics.pairwise import pairwise_distances

In [31]:
# Creating the User Similarity Matrix using pairwise_distance function.
user_correlation = 1 - pairwise_distances(df_subtracted.fillna(0), metric='cosine')
user_correlation[np.isnan(user_correlation)] = 0
print(user_correlation)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [32]:
user_correlation.shape

(17868, 17868)

## Prediction - User User

Doing the prediction for the users which are positively related with other users, and not the users which are negatively related as we are interested in the users which are more similar to the current users. So, ignoring the correlation for values less than 0. 

In [33]:
user_correlation[user_correlation<0]=0
user_correlation

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

Rating predicted by the user (for movies rated as well as not rated) is the weighted sum of correlation with the movie rating (as present in the rating dataset). 

In [34]:
user_predicted_ratings = np.dot(user_correlation, df_pivot.fillna(0))
user_predicted_ratings

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 3.03064063, 0.        , ..., 0.77051412, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [35]:
user_predicted_ratings.shape

(17868, 256)

In [36]:
user_predicted_ratings

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 3.03064063, 0.        , ..., 0.77051412, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

Since we are interested only in the movies not rated by the user, we will ignore the movies rated by the user by making it zero. 

In [37]:
user_final_rating = np.multiply(user_predicted_ratings,dummy_train)
user_final_rating.head()

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  ...  Yes To Grapefruit Rejuvenating Body Wash
reviews_username                                                                 ...                                          
00dog3                                                          0.0              ...                                       0.0
00sab00                                                         0.0              ...                                       0.0
01impala                                                        0.0              ...                                       0.0
02dakota                                                        0.0              ...                                       0.0
02deuce                                                         0.0              ...                                       0.0

[5 rows x 256 columns]

### Finding the top 5 recommendation for the *user*

In [38]:
# Take the user ID as input.
user_input = str(input("Enter your user name"))
print(user_input)

Enter your user name00dog3
00dog3


In [39]:
user_final_rating.head(20)

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  ...  Yes To Grapefruit Rejuvenating Body Wash
reviews_username                                                                 ...                                          
00dog3                                                          0.0              ...                                    0.0000
00sab00                                                         0.0              ...                                    0.0000
01impala                                                        0.0              ...                                    0.0000
02dakota                                                        0.0              ...                                    0.0000
02deuce                                                         0.0              ...                                    0.0000
0325home                                                        0.0              ...                                    0.0000
06stidriver                                                     0.0              ...                                    0.0000
09mommy11                                                       0.0              ...                                    0.0000
1085                                                            0.0              ...                                    0.0000
10ten                                                           0.0              ...                                    0.0000
1143mom                                                         0.0              ...                                    0.0000
11677j                                                          0.0              ...                                    0.0000
1234                                                            0.0              ...                                    0.3698
1234561                                                         0.0              ...                                    0.0000
1234567                                                         0.0              ...                                    0.0000
1234asdf                                                        0.0              ...                                    0.0000
123charlie                                                      0.0              ...                                    0.0000
123numbers                                                      0.0              ...                                    0.0000
123soccermom                                                    0.0              ...                                    0.0000
123too                                                          0.0              ...                                    0.0000

[20 rows x 256 columns]

In [40]:
d = user_final_rating.loc[user_input].sort_values(ascending=False)[0:20]
d

name
Yes To Grapefruit Rejuvenating Body Wash                                     0.0
Yes To Carrots Nourishing Body Wash                                          0.0
Heinz Tomato Ketchup, 38oz                                                   0.0
Head & Shoulders Dandruff Shampoo Ocean Lift 2 In 1                          0.0
Head & Shoulders Classic Clean Conditioner                                   0.0
Hawaiian Punch Berry Limeade Blast Juice                                     0.0
Happy Tot Apple and Butternut Squash                                         0.0
Godzilla 3d Includes Digital Copy Ultraviolet 3d/2d Blu-Ray/dvd              0.0
Germ Guardian174 Elite 3-In-1 Pet Pure True Hepa Air Purifier Ac4300bptca    0.0
Gain Original Scent Liquid Fabric Softener 129 Oz                            0.0
Fiskars174 Classic Stick Rotary Cutter (45 Mm)                               0.0
Finish Quantum Dishwasher Detergent, Lemon Sparkle Scent, 45 Count           0.0
Finish Gelpacs Dishwash

# Evaluation - User User 

Evaluation will we same as you have seen above for the prediction. The only difference being, you will evaluate for the movie already rated by the user insead of predicting it for the movie not rated by the user. 

In [41]:
# Find out the common users of test and train dataset.
common = test[test.reviews_username.isin(train.reviews_username)]
common.shape

(1075, 3)

In [42]:
common.head()

reviews_username  ... reviews_rating
12055            jilly  ...            5.0
24307            steph  ...            1.0
7333      disappointed  ...            2.0
7603             donna  ...            4.0
12072            jimbo  ...            4.5

[5 rows x 3 columns]

In [43]:
# convert into the user-movie matrix.
common_user_based_matrix = common.pivot_table(index='reviews_username', columns='name', values='reviews_rating')

In [44]:
common_user_based_matrix.head()

name              100:Complete First Season (blu-Ray)  ...  Yes To Grapefruit Rejuvenating Body Wash
reviews_username                                       ...                                          
1234                                              NaN  ...                                       NaN
1943                                              NaN  ...                                       NaN
1witch                                            NaN  ...                                       NaN
50cal                                             NaN  ...                                       NaN
aaron                                             NaN  ...                                       NaN

[5 rows x 121 columns]

In [45]:
common_user_based_matrix.shape

(890, 121)

In [46]:
# Convert the user_correlation matrix into dataframe.
user_correlation_df = pd.DataFrame(user_correlation)

In [47]:
user_correlation_df.head()

0      1      2      3      4      ...  17863  17864  17865  17866  17867
0    0.0    0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0
1    0.0    1.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0
2    0.0    0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0
3    0.0    0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0
4    0.0    0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0

[5 rows x 17868 columns]

In [48]:
user_correlation_df.shape

(17868, 17868)

In [49]:
df_subtracted.head(1)

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  ...  Yes To Grapefruit Rejuvenating Body Wash
reviews_username                                                                 ...                                          
00dog3                                                          NaN              ...                                       NaN

[1 rows x 256 columns]

In [50]:
df_subtracted.shape

(17868, 256)

In [51]:
user_correlation_df['reviews_username'] = df_subtracted.index

user_correlation_df.set_index('reviews_username',inplace=True)
user_correlation_df.head()

0      1      2      3      ...  17864  17865  17866  17867
reviews_username                              ...                            
00dog3              0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0
00sab00             0.0    1.0    0.0    0.0  ...    0.0    0.0    0.0    0.0
01impala            0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0
02dakota            0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0
02deuce             0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0

[5 rows x 17868 columns]

In [52]:
user_correlation_df.shape

(17868, 17868)

In [53]:
common.head(3)

reviews_username  ... reviews_rating
12055            jilly  ...            5.0
24307            steph  ...            1.0
7333      disappointed  ...            2.0

[3 rows x 3 columns]

In [54]:
list_name = common.reviews_username.tolist()

user_correlation_df.columns = df_subtracted.index.tolist()


user_correlation_df_1 =  user_correlation_df[user_correlation_df.index.isin(list_name)]

In [ ]:
# list_name

In [55]:
user_correlation_df.shape

(17868, 17868)

In [56]:
user_correlation_df_1.shape

(890, 17868)

In [57]:
user_correlation_df_2 = user_correlation_df_1.T[user_correlation_df_1.T.index.isin(list_name)]

In [58]:
user_correlation_df_3 = user_correlation_df_2.T

In [59]:
user_correlation_df_3.head()

1234  1943  1witch  50cal  ...  xavier  xstr8edgex  yeyo  zach
reviews_username                             ...                                
1234               1.0   0.0     0.0    0.0  ...     0.0         0.0   0.0   0.0
1943               0.0   0.0     0.0    0.0  ...     0.0         0.0   0.0   0.0
1witch             0.0   0.0     0.0    0.0  ...     0.0         0.0   0.0   0.0
50cal              0.0   0.0     0.0    0.0  ...     0.0         0.0   0.0   0.0
aaron              0.0   0.0     0.0    0.0  ...     0.0         0.0   0.0   0.0

[5 rows x 890 columns]

In [60]:
user_correlation_df_3.shape

(890, 890)

In [61]:
user_correlation_df_3[user_correlation_df_3<0]=0

common_user_predicted_ratings = np.dot(user_correlation_df_3, common_user_based_matrix.fillna(0))
common_user_predicted_ratings

array([[0.       , 3.2620217, 0.       , ..., 1.0161846, 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       ...,
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ]])

In [65]:
common_user_predicted_ratings.shape

(890, 121)

In [66]:
common.shape

(1075, 3)

In [67]:
dummy_test = common.copy()

dummy_test['reviews_rating'] = dummy_test['reviews_rating'].apply(lambda x: 1 if x>=1 else 0)

dummy_test = dummy_test.pivot_table(index='reviews_username', columns='name', values='reviews_rating').fillna(0)

In [68]:
dummy_test.shape

(890, 121)

In [69]:
common_user_based_matrix.head()

name              100:Complete First Season (blu-Ray)  ...  Yes To Grapefruit Rejuvenating Body Wash
reviews_username                                       ...                                          
1234                                              NaN  ...                                       NaN
1943                                              NaN  ...                                       NaN
1witch                                            NaN  ...                                       NaN
50cal                                             NaN  ...                                       NaN
aaron                                             NaN  ...                                       NaN

[5 rows x 121 columns]

In [70]:
dummy_test.head()

name              100:Complete First Season (blu-Ray)  ...  Yes To Grapefruit Rejuvenating Body Wash
reviews_username                                       ...                                          
1234                                              0.0  ...                                       0.0
1943                                              0.0  ...                                       0.0
1witch                                            0.0  ...                                       0.0
50cal                                             0.0  ...                                       0.0
aaron                                             0.0  ...                                       0.0

[5 rows x 121 columns]

In [71]:
common_user_predicted_ratings = np.multiply(common_user_predicted_ratings,dummy_test)

In [72]:
common_user_predicted_ratings.head()

name              100:Complete First Season (blu-Ray)  ...  Yes To Grapefruit Rejuvenating Body Wash
reviews_username                                       ...                                          
1234                                              0.0  ...                                       0.0
1943                                              0.0  ...                                       0.0
1witch                                            0.0  ...                                       0.0
50cal                                             0.0  ...                                       0.0
aaron                                             0.0  ...                                       0.0

[5 rows x 121 columns]

Calculating the RMSE for only the movies rated by user. For RMSE, normalising the rating to (1,5) range.

In [74]:
from sklearn.preprocessing import MinMaxScaler
from numpy import *

X  = common_user_predicted_ratings.copy() 
X = X[X>0]

scaler = MinMaxScaler(feature_range=(1, 5))
print(scaler.fit(X))
y = (scaler.transform(X))

print(y)

MinMaxScaler(copy=True, feature_range=(1, 5))
[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]


/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_data.py:375: RuntimeWarning: All-NaN slice encountered
  data_min = np.nanmin(X, axis=0)
/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_data.py:376: RuntimeWarning: All-NaN slice encountered
  data_max = np.nanmax(X, axis=0)


In [75]:
common_ = common.pivot_table(index='reviews_username', columns='name', values='reviews_rating')

In [76]:
# Finding total non-NaN value
total_non_nan = np.count_nonzero(~np.isnan(y))

In [77]:
rmse = (sum(sum((common_ - y )**2))/total_non_nan)**0.5
print(rmse)

2.5796439184075854


## Using Item similarity

# Item Based Similarity

Taking the transpose of the rating matrix to normalize the rating around the mean for different movie ID. In the user based similarity, we had taken mean for each user instead of each movie. 

In [78]:
df_pivot = train.pivot(
    index='reviews_username',
    columns='name',
    values='reviews_rating'
).T

df_pivot.head()

reviews_username                                    00dog3  ...  zzz1127
name                                                        ...         
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...     NaN  ...      NaN
100:Complete First Season (blu-Ray)                    NaN  ...      NaN
2017-2018 Brownline174 Duraflex 14-Month Planne...     NaN  ...      NaN
2x Ultra Era with Oxi Booster, 50fl oz                 NaN  ...      NaN
42 Dual Drop Leaf Table with 2 Madrid Chairs"          NaN  ...      NaN

[5 rows x 17868 columns]

Normalising the movie rating for each movie for using the Adujsted Cosine

In [79]:
mean = np.nanmean(df_pivot, axis=1)
df_subtracted = (df_pivot.T-mean).T

In [80]:
df_subtracted.head()

reviews_username                                    00dog3  ...  zzz1127
name                                                        ...         
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...     NaN  ...      NaN
100:Complete First Season (blu-Ray)                    NaN  ...      NaN
2017-2018 Brownline174 Duraflex 14-Month Planne...     NaN  ...      NaN
2x Ultra Era with Oxi Booster, 50fl oz                 NaN  ...      NaN
42 Dual Drop Leaf Table with 2 Madrid Chairs"          NaN  ...      NaN

[5 rows x 17868 columns]

Finding the cosine similarity using pairwise distances approach

In [81]:
from sklearn.metrics.pairwise import pairwise_distances

In [82]:
# Item Similarity Matrix
item_correlation = 1 - pairwise_distances(df_subtracted.fillna(0), metric='cosine')
item_correlation[np.isnan(item_correlation)] = 0
print(item_correlation)

[[ 1.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          1.          0.         ... -0.00512307  0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 ...
 [ 0.         -0.00512307  0.         ...  1.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          1.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   1.        ]]


In [83]:
item_correlation.shape

(256, 256)

Filtering the correlation only for which the value is greater than 0. (Positively correlated)

In [84]:
item_correlation[item_correlation<0]=0
item_correlation

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

# Prediction - Item Item

In [85]:
item_predicted_ratings = np.dot((df_pivot.fillna(0).T),item_correlation)
item_predicted_ratings

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.00084707, 0.        , ..., 0.00211006, 0.        ,
        0.        ],
       [0.        , 0.015696  , 0.        , ..., 0.        , 0.        ,
        0.01186601],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [86]:
item_predicted_ratings.shape

(17868, 256)

In [87]:
dummy_train.shape

(17868, 256)

### Filtering the rating only for the movies not rated by the user for recommendation

In [88]:
item_final_rating = np.multiply(item_predicted_ratings,dummy_train)
item_final_rating.head()

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  ...  Yes To Grapefruit Rejuvenating Body Wash
reviews_username                                                                 ...                                          
00dog3                                                          0.0              ...                                  0.000000
00sab00                                                         0.0              ...                                  0.000000
01impala                                                        0.0              ...                                  0.011866
02dakota                                                        0.0              ...                                  0.019777
02deuce                                                         0.0              ...                                  0.015821

[5 rows x 256 columns]

In [89]:
item_final_rating

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  ...  Yes To Grapefruit Rejuvenating Body Wash
reviews_username                                                                 ...                                          
00dog3                                                          0.0              ...                                  0.000000
00sab00                                                         0.0              ...                                  0.000000
01impala                                                        0.0              ...                                  0.011866
02dakota                                                        0.0              ...                                  0.019777
02deuce                                                         0.0              ...                                  0.015821
...                                                             ...              ...                                       ...
zwithanx                                                        0.0              ...                                  0.000000
zxcsdfd                                                         0.0              ...                                  0.000000
zyiah4                                                          0.0              ...                                  0.000000
zzdiane                                                         0.0              ...                                  0.000000
zzz1127                                                         0.0              ...                                  0.000000

[17868 rows x 256 columns]

### Finding the top 5 recommendation for the *user*



In [90]:
# Take the user ID as input
user_input = str(input("Enter your user name"))
print(user_input)

Enter your user name00dog3
00dog3


In [91]:
item_final_rating.head(20)

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  ...  Yes To Grapefruit Rejuvenating Body Wash
reviews_username                                                                 ...                                          
00dog3                                                          0.0              ...                                  0.000000
00sab00                                                         0.0              ...                                  0.000000
01impala                                                        0.0              ...                                  0.011866
02dakota                                                        0.0              ...                                  0.019777
02deuce                                                         0.0              ...                                  0.015821
0325home                                                        0.0              ...                                  0.000000
06stidriver                                                     0.0              ...                                  0.000000
09mommy11                                                       0.0              ...                                  0.000000
1085                                                            0.0              ...                                  0.000000
10ten                                                           0.0              ...                                  0.000000
1143mom                                                         0.0              ...                                  0.000000
11677j                                                          0.0              ...                                  0.000000
1234                                                            0.0              ...                                  0.015821
1234561                                                         0.0              ...                                  0.000000
1234567                                                         0.0              ...                                  0.000000
1234asdf                                                        0.0              ...                                  0.000000
123charlie                                                      0.0              ...                                  0.015821
123numbers                                                      0.0              ...                                  0.019777
123soccermom                                                    0.0              ...                                  0.000000
123too                                                          0.0              ...                                  0.000000

[20 rows x 256 columns]

In [92]:
# Recommending the Top 5 products to the user.
d = pd.DataFrame(item_final_rating.loc[user_input].sort_values(ascending=False)[0:20])
d

00dog3
name                                                        
Mike Dave Need Wedding Dates (dvd + Digital)        0.030040
Caress Moisturizing Body Bar Natural Silk, 4.75oz   0.023561
Planes: Fire Rescue (2 Discs) (includes Digital...  0.007925
Burt's Bees Lip Shimmer, Raisin                     0.007837
Clorox Disinfecting Wipes Value Pack Scented 15...  0.002464
Head & Shoulders Dandruff Shampoo Ocean Lift 2 ...  0.000000
Head & Shoulders Classic Clean Conditioner          0.000000
Hawaiian Punch Berry Limeade Blast Juice            0.000000
Happy Tot Apple and Butternut Squash                0.000000
Godzilla 3d Includes Digital Copy Ultraviolet 3...  0.000000
Germ Guardian174 Elite 3-In-1 Pet Pure True Hep...  0.000000
Gain Original Scent Liquid Fabric Softener 129 Oz   0.000000
Fiskars174 Classic Stick Rotary Cutter (45 Mm)      0.000000
Finish Quantum Dishwasher Detergent, Lemon Spar...  0.000000
Finish Gelpacs Dishwasher Detergent, Orange Sce...  0.000000
Feit 60-Watt A19 Gu24 Base Led Light Bulb - Sof...  0.000000
Fantasy Fields Lil' Sports Fan Step Stool - Tea...  0.000000
Heiress (dvd)                                       0.000000
Equals (blu-Ray)                                    0.000000
Elvis Presley - Girl Happy (cd)                     0.000000

In [93]:
c = d.index.to_list()

In [94]:
c

['Mike Dave Need Wedding Dates (dvd + Digital)',
 'Caress Moisturizing Body Bar Natural Silk, 4.75oz',
 'Planes: Fire Rescue (2 Discs) (includes Digital Copy) (blu-Ray/dvd)',
 "Burt's Bees Lip Shimmer, Raisin",
 'Clorox Disinfecting Wipes Value Pack Scented 150 Ct Total',
 'Head & Shoulders Dandruff Shampoo Ocean Lift 2 In 1',
 'Head & Shoulders Classic Clean Conditioner',
 'Hawaiian Punch Berry Limeade Blast Juice',
 'Happy Tot Apple and Butternut Squash',
 'Godzilla 3d Includes Digital Copy Ultraviolet 3d/2d Blu-Ray/dvd',
 'Germ Guardian174 Elite 3-In-1 Pet Pure True Hepa Air Purifier Ac4300bptca',
 'Gain Original Scent Liquid Fabric Softener 129 Oz',
 'Fiskars174 Classic Stick Rotary Cutter (45 Mm)',
 'Finish Quantum Dishwasher Detergent, Lemon Sparkle Scent, 45 Count',
 'Finish Gelpacs Dishwasher Detergent, Orange Scent, 84ct',
 'Feit 60-Watt A19 Gu24 Base Led Light Bulb - Soft White',
 "Fantasy Fields Lil' Sports Fan Step Stool - Teamson",
 'Heiress (dvd)',
 'Equals (blu-Ray)',
 '

# Evaluation - Item Item

Evaluation will we same as you have seen above for the prediction. The only difference being, you will evaluate for the movie already rated by the user insead of predicting it for the movie not rated by the user. 

In [95]:
test.columns

Index(['reviews_username', 'name', 'reviews_rating'], dtype='object')

In [96]:
common =  test[test.name.isin(train.name)]
common.shape

(8262, 3)

In [97]:
common.head(4)

reviews_username  ... reviews_rating
20677             pinky  ...            5.0
21790           rlester  ...            5.0
7644   dookier4thelungs  ...            5.0
4098            bymissy  ...            5.0

[4 rows x 3 columns]

In [98]:
common_item_based_matrix = common.pivot_table(index='reviews_username', columns='name', values='reviews_rating').T

In [99]:
common_item_based_matrix.shape

(200, 7922)

In [100]:
item_correlation_df = pd.DataFrame(item_correlation)

In [101]:
item_correlation_df.head(1)

0    1    2    3    4    5    6    ...  249  250  251  252  253  254  255
0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0

[1 rows x 256 columns]

In [102]:
item_correlation_df['name'] = df_subtracted.index
item_correlation_df.set_index('name',inplace=True)
item_correlation_df.head()

0    1    ...  254  255
name                                                          ...          
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...  1.0  0.0  ...  0.0  0.0
100:Complete First Season (blu-Ray)                 0.0  1.0  ...  0.0  0.0
2017-2018 Brownline174 Duraflex 14-Month Planne...  0.0  0.0  ...  0.0  0.0
2x Ultra Era with Oxi Booster, 50fl oz              0.0  0.0  ...  0.0  0.0
42 Dual Drop Leaf Table with 2 Madrid Chairs"       0.0  0.0  ...  0.0  0.0

[5 rows x 256 columns]

In [103]:
list_name = common.name.tolist()

In [104]:
item_correlation_df.columns = df_subtracted.index.tolist()

item_correlation_df_1 =  item_correlation_df[item_correlation_df.index.isin(list_name)]

In [105]:
item_correlation_df_2 = item_correlation_df_1.T[item_correlation_df_1.T.index.isin(list_name)]

item_correlation_df_3 = item_correlation_df_2.T

In [106]:
item_correlation_df_3.head()

0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  ...  Yes To Grapefruit Rejuvenating Body Wash
name                                                                                                               ...                                          
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...                                                1.0              ...                                       0.0
100:Complete First Season (blu-Ray)                                                               0.0              ...                                       0.0
2017-2018 Brownline174 Duraflex 14-Month Planne...                                                0.0              ...                                       0.0
2x Ultra Era with Oxi Booster, 50fl oz                                                            0.0              ...                                       0.0
4C Grated Parmesan Cheese 100% Natural 8oz Shaker                                                 0.0              ...                                       0.0

[5 rows x 200 columns]

In [107]:
item_correlation_df_3[item_correlation_df_3<0]=0

common_item_predicted_ratings = np.dot(item_correlation_df_3, common_item_based_matrix.fillna(0))
common_item_predicted_ratings


array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [5.        , 0.        , 0.        , ..., 0.02616   , 0.02028243,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.01977669, 0.        ,
        0.        ]])

In [108]:
common_item_predicted_ratings.shape

(200, 7922)

Dummy test will be used for evaluation. To evaluate, we will only make prediction on the movies rated by the user. So, this is marked as 1. This is just opposite of dummy_train



In [109]:
dummy_test = common.copy()

dummy_test['reviews_rating'] = dummy_test['reviews_rating'].apply(lambda x: 1 if x>=1 else 0)

dummy_test = dummy_test.pivot_table(index='reviews_username', columns='name', values='reviews_rating').T.fillna(0)

common_item_predicted_ratings = np.multiply(common_item_predicted_ratings,dummy_test)

The products not rated is marked as 0 for evaluation. And make the item- item matrix representaion.


In [110]:
common_ = common.pivot_table(index='reviews_username', columns='name', values='reviews_rating').T

In [111]:
from sklearn.preprocessing import MinMaxScaler
from numpy import *

X  = common_item_predicted_ratings.copy() 
X = X[X>0]

scaler = MinMaxScaler(feature_range=(1, 5))
print(scaler.fit(X))
y = (scaler.transform(X))

print(y)

MinMaxScaler(copy=True, feature_range=(1, 5))
[[nan nan nan ... nan nan nan]
 [ 1. nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]


/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_data.py:375: RuntimeWarning: All-NaN slice encountered
  data_min = np.nanmin(X, axis=0)
/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_data.py:376: RuntimeWarning: All-NaN slice encountered
  data_max = np.nanmax(X, axis=0)


In [112]:
# Finding total non-NaN value
total_non_nan = np.count_nonzero(~np.isnan(y))

In [113]:
rmse = (sum(sum((common_ - y )**2))/total_non_nan)**0.5
print(rmse)

3.579123293831438


##**Summary - Recommendation Engine**

In [114]:
df_reco = pd.read_csv('/content/drive/MyDrive/Capstone/Product Recommender system/processed.csv')

In [115]:
df_reco

Unnamed: 0  ...                                          processed
0               0  ...  ['awesome', 'love', 'album', 'i', 'good', 'hip...
1               1  ...  ['good', 'good', 'flavor', 'review', 'collect'...
2               2  ...                         ['good', 'good', 'flavor']
3               3  ...  ['disappoint', 'read', 'review', 'look', 'buy'...
4               4  ...  ['ifrit', 'husband', 'bought', 'gel', 'u', 'ge...
...           ...  ...                                                ...
29995       29995  ...  ['soft', 'got', 'condition', 'influence', 'tri...
29996       29996  ...  ['love', 'love', 'receiv', 'review', 'purpose'...
29997       29997  ...  ['hair', 'smooth', 'use', 'first', 'love', 'sm...
29998       29998  ...  ['perfect', 'oil', 'hair', 'receiv', 'influenc...
29999       29999  ...  ['conduit', 'health', 'receiv', 'product', 'co...

[30000 rows x 7 columns]

In [116]:
df_reco2 = pd.read_csv('/content/drive/MyDrive/Capstone/Product Recommender system/sample30.csv')

In [117]:
df_reco2

id            brand  ... reviews_username user_sentiment
0      AV13O1A8GV-KLJ3akUyj  Universal Music  ...           joshua       Positive
1      AV14LG0R-jtxr-f38QfS         Lundberg  ...        dorothy w       Positive
2      AV14LG0R-jtxr-f38QfS         Lundberg  ...        dorothy w       Positive
3      AV16khLE-jtxr-f38VFn              K-Y  ...          rebecca       Negative
4      AV16khLE-jtxr-f38VFn              K-Y  ...        walker557       Negative
...                     ...              ...  ...              ...            ...
29995  AVpfW8y_LJeJML437ySW    L'oreal Paris  ...       laurasnchz       Positive
29996  AVpfW8y_LJeJML437ySW    L'oreal Paris  ...    scarlepadilla       Positive
29997  AVpfW8y_LJeJML437ySW    L'oreal Paris  ...       liviasuexo       Positive
29998  AVpfW8y_LJeJML437ySW    L'oreal Paris  ...         ktreed95       Positive
29999  AVpfW8y_LJeJML437ySW    L'oreal Paris  ...        kcoopxoxo       Positive

[30000 rows x 15 columns]

In [118]:
df_reco['reviews_username'] = df_reco2['reviews_username']

In [119]:
df_reco.drop(columns=['Unnamed: 0'],inplace=
             True)

In [123]:
df_reco['name'] = df_reco2['name']

In [131]:
df_reco['user_sentiment'] = df_reco2['user_sentiment']

In [124]:
df_reco.columns

Index(['reviews_rating', 'reviews_text', 'reviews_title', 'user_sentiment',
       'merged', 'processed', 'reviews_username', 'name'],
      dtype='object')

In [132]:
df_reco.to_csv('/content/drive/MyDrive/Capstone/Product Recommender system/processednew.csv')

In [133]:
df_reco_final = df_reco[['processed','name','reviews_username','user_sentiment']]

In [134]:
df_reco_final

processed  ... user_sentiment
0      ['awesome', 'love', 'album', 'i', 'good', 'hip...  ...       Positive
1      ['good', 'good', 'flavor', 'review', 'collect'...  ...       Positive
2                             ['good', 'good', 'flavor']  ...       Positive
3      ['disappoint', 'read', 'review', 'look', 'buy'...  ...       Negative
4      ['ifrit', 'husband', 'bought', 'gel', 'u', 'ge...  ...       Negative
...                                                  ...  ...            ...
29995  ['soft', 'got', 'condition', 'influence', 'tri...  ...       Positive
29996  ['love', 'love', 'receiv', 'review', 'purpose'...  ...       Positive
29997  ['hair', 'smooth', 'use', 'first', 'love', 'sm...  ...       Positive
29998  ['perfect', 'oil', 'hair', 'receiv', 'influenc...  ...       Positive
29999  ['conduit', 'health', 'receiv', 'product', 'co...  ...       Positive

[30000 rows x 4 columns]

In [135]:
type(df_reco_final['processed'][0])

str

In [136]:
newdf = df_reco_final[df_reco_final.name.isin(c)]

In [137]:
newdf

processed  ... user_sentiment
1225   ['expect', 'product', 'ok', 'scent', 'bare', '...  ...       Positive
1226   ['usable', 'long', 'run', 'expense', 're', 'el...  ...       Positive
1227   ['spark', 'shine', 'glitter', 'glow', 'finish'...  ...       Positive
1228   ['better', 'cheaper', 'finish', 'cheaper', 'fi...  ...       Positive
1229         ['love', 'smell', 'love', 'lemon', 'smell']  ...       Positive
...                                                  ...  ...            ...
28360  ['awesome', 'movi', 'yo', 'love', 'movi', 'lov...  ...       Positive
28361  ['awesome', 'movi', 'bought', 'two', 'young', ...  ...       Positive
28362  ['two', 'son', 'love', 'movi', 'better', 'firs...  ...       Positive
28363  ['grandson', 'thrill', 'find', 'anywher', 'ord...  ...       Positive
28364  ['much', 'advance', 'topic', 'first', 'movi', ...  ...       Positive

[14924 rows x 4 columns]

In [140]:
newdf['processed'] = newdf['processed'].apply(lambda X: re.sub('[\[\],\']','',X))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [145]:
type(newdf['processed'][28364])

str

In [148]:
filename1 = '/content/drive/MyDrive/Capstone/Product Recommender system/word_vec.pkl'
vec = pickle.load(open(filename1, 'rb'))

In [149]:
transformed = vec.transform(newdf['processed'])

In [150]:
transformed

<14924x9692 sparse matrix of type '<class 'numpy.float64'>'
	with 191612 stored elements in Compressed Sparse Row format>

In [151]:
filename = '/content/drive/MyDrive/Capstone/Product Recommender system/random_model.pkl'
model = pickle.load(open(filename, 'rb'))

In [153]:
sent_op = model.predict(transformed)

In [216]:
sent_op

array(['Positive', 'Positive', 'Positive', ..., 'Positive', 'Positive',
       'Positive'], dtype=object)

In [215]:
newdf['user_sentiment'] = sent_op

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [167]:
from collections import Counter


In [217]:
Counter(newdf['user_sentiment'])

Counter({'Negative': 1303, 'Positive': 13621})

In [218]:
newdf['user_sentiment'] = newdf['user_sentiment'].map({'Negative': -1, 'Positive': 1})

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [228]:
newdf['user_sentiment'].unique()

array([ 1, -1])

In [229]:
newdf

processed  ... user_sentiment
1225           expect product ok scent bare notice overr  ...              1
1226   usable long run expense re elect bill bought l...  ...              1
1227   spark shine glitter glow finish dirt finish qu...  ...              1
1228   better cheaper finish cheaper finish leav whit...  ...              1
1229                         love smell love lemon smell  ...              1
...                                                  ...  ...            ...
28360          awesome movi yo love movi love combo pack  ...              1
28361  awesome movi bought two young boy hit thorough...  ...              1
28362          two son love movi better first plane movi  ...              1
28363  grandson thrill find anywher order yr old gran...  ...              1
28364  much advance topic first movi movi much fun wo...  ...              1

[14924 rows x 4 columns]

In [245]:
#d = pd.DataFrame((newdf.groupby(['name'])['user_sentiment'].sum()/newdf.groupby(['name'])['user_sentiment'].count())*100).reset_index()
d = pd.DataFrame(newdf.groupby(['name'])['user_sentiment'].sum())


In [241]:
newdf.groupby(['name'])['user_sentiment'].count().values

array([ 873,   68, 8545,    1,   13,    1,    8,    8,   35,    5,    6,
          1, 3325,    9,   22,   86,    6,   12,  757, 1143])

In [246]:
d['sum'] = newdf.groupby(['name'])['user_sentiment'].sum().values 
d['count'] = newdf.groupby(['name'])['user_sentiment'].count().values

In [247]:
d = d.sort_values(by = ['user_sentiment'],ascending=False)[0:20]

In [248]:
d

user_sentiment   sum  count
name                                                                           
Clorox Disinfecting Wipes Value Pack Scented 15...            7043  7043   8545
Godzilla 3d Includes Digital Copy Ultraviolet 3...            2825  2825   3325
Planes: Fire Rescue (2 Discs) (includes Digital...            1017  1017   1143
Burt's Bees Lip Shimmer, Raisin                                669   669    873
Mike Dave Need Wedding Dates (dvd + Digital)                   555   555    757
Head & Shoulders Classic Clean Conditioner                      74    74     86
Caress Moisturizing Body Bar Natural Silk, 4.75oz               52    52     68
Finish Quantum Dishwasher Detergent, Lemon Spar...              27    27     35
Hawaiian Punch Berry Limeade Blast Juice                        20    20     22
Equals (blu-Ray)                                                 7     7     13
Head & Shoulders Dandruff Shampoo Ocean Lift 2 ...               6     6      6
Gain Original Scent Liquid Fabric Softener 129 Oz                6     6      6
Happy Tot Apple and Butternut Squash                             5     5      9
Finish Gelpacs Dishwasher Detergent, Orange Sce...               4     4      8
Feit 60-Watt A19 Gu24 Base Led Light Bulb - Sof...               2     2      8
Heiress (dvd)                                                    2     2     12
Fantasy Fields Lil' Sports Fan Step Stool - Tea...               1     1      1
Fiskars174 Classic Stick Rotary Cutter (45 Mm)                   1     1      5
Germ Guardian174 Elite 3-In-1 Pet Pure True Hep...               1     1      1
Elvis Presley - Girl Happy (cd)                                  1     1      1

In [244]:
d

name  ...  count
10  Gain Original Scent Liquid Fabric Softener 129 Oz  ...      6
11  Germ Guardian174 Elite 3-In-1 Pet Pure True He...  ...      1
16  Head & Shoulders Dandruff Shampoo Ocean Lift 2...  ...      6
3                     Elvis Presley - Girl Happy (cd)  ...      1
5   Fantasy Fields Lil' Sports Fan Step Stool - Te...  ...      1
14           Hawaiian Punch Berry Limeade Blast Juice  ...     22
19  Planes: Fire Rescue (2 Discs) (includes Digita...  ...   1143
15         Head & Shoulders Classic Clean Conditioner  ...     86
12  Godzilla 3d Includes Digital Copy Ultraviolet ...  ...   3325
2   Clorox Disinfecting Wipes Value Pack Scented 1...  ...   8545
8   Finish Quantum Dishwasher Detergent, Lemon Spa...  ...     35
0                     Burt's Bees Lip Shimmer, Raisin  ...    873
1   Caress Moisturizing Body Bar Natural Silk, 4.75oz  ...     68
18       Mike Dave Need Wedding Dates (dvd + Digital)  ...    757
13               Happy Tot Apple and Butternut Squash  ...      9
4                                    Equals (blu-Ray)  ...     13
7   Finish Gelpacs Dishwasher Detergent, Orange Sc...  ...      8
6   Feit 60-Watt A19 Gu24 Base Led Light Bulb - So...  ...      8
9      Fiskars174 Classic Stick Rotary Cutter (45 Mm)  ...      5
17                                      Heiress (dvd)  ...     12

[20 rows x 4 columns]