# Recommendation System Notebook
- User based recommendation
- User based prediction & evaluation
- Item based recommendation
- Item based prediction & evaluation

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


Different Approaches to develop Recommendation System -

1. Demographich based Recommendation System

2. Content Based Recommendation System

3. Collaborative filtering Recommendation System

In [4]:
# import libraties
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sys

In [ ]:
# Reading ratings file from GitHub. # MovieLens
ratings = pd.read_csv('https://raw.githubusercontent.com/antrikshsaxena/NLPCapstone/main/ratings_final.csv' , encoding='latin-1')
ratings.head()

userId  movieId  rating   timestamp
0       1      296     5.0  1147880044
1       1      306     3.5  1147868817
2       1      307     5.0  1147868828
3       1      665     5.0  1147878820
4       1      899     3.5  1147868510

In [5]:
sys.path.append('/content/drive/MyDrive/Capstone/Product Recommender system')

In [43]:
df = pd.read_csv('/content/drive/MyDrive/Capstone/Product Recommender system/sample30.csv')

In [44]:
df

id            brand  ... reviews_username user_sentiment
0      AV13O1A8GV-KLJ3akUyj  Universal Music  ...           joshua       Positive
1      AV14LG0R-jtxr-f38QfS         Lundberg  ...        dorothy w       Positive
2      AV14LG0R-jtxr-f38QfS         Lundberg  ...        dorothy w       Positive
3      AV16khLE-jtxr-f38VFn              K-Y  ...          rebecca       Negative
4      AV16khLE-jtxr-f38VFn              K-Y  ...        walker557       Negative
...                     ...              ...  ...              ...            ...
29995  AVpfW8y_LJeJML437ySW    L'oreal Paris  ...       laurasnchz       Positive
29996  AVpfW8y_LJeJML437ySW    L'oreal Paris  ...    scarlepadilla       Positive
29997  AVpfW8y_LJeJML437ySW    L'oreal Paris  ...       liviasuexo       Positive
29998  AVpfW8y_LJeJML437ySW    L'oreal Paris  ...         ktreed95       Positive
29999  AVpfW8y_LJeJML437ySW    L'oreal Paris  ...        kcoopxoxo       Positive

[30000 rows x 15 columns]

In [45]:
col = ['name','reviews_rating','reviews_username']

In [46]:
df_master = df[col]

In [47]:
df_master

name  ...  reviews_username
0              Pink Friday: Roman Reloaded Re-Up (w/dvd)  ...            joshua
1             Lundberg Organic Cinnamon Toast Rice Cakes  ...         dorothy w
2             Lundberg Organic Cinnamon Toast Rice Cakes  ...         dorothy w
3                       K-Y Love Sensuality Pleasure Gel  ...           rebecca
4                       K-Y Love Sensuality Pleasure Gel  ...         walker557
...                                                  ...  ...               ...
29995  L'or233al Paris Elvive Extraordinary Clay Reba...  ...        laurasnchz
29996  L'or233al Paris Elvive Extraordinary Clay Reba...  ...     scarlepadilla
29997  L'or233al Paris Elvive Extraordinary Clay Reba...  ...        liviasuexo
29998  L'or233al Paris Elvive Extraordinary Clay Reba...  ...          ktreed95
29999  L'or233al Paris Elvive Extraordinary Clay Reba...  ...         kcoopxoxo

[30000 rows x 3 columns]

In [48]:
df_master.groupby(by=["reviews_username","name"]).mean()

reviews_rating
reviews_username name                                                              
00dog3           Chex Muddy Buddies Brownie Supreme Snack Mix                   4.0
00sab00          Mike Dave Need Wedding Dates (dvd + Digital)                   1.0
                 My Big Fat Greek Wedding 2 (blu-Ray + Dvd + Dig...             3.0
01impala         Godzilla 3d Includes Digital Copy Ultraviolet 3...             3.0
02dakota         Godzilla 3d Includes Digital Copy Ultraviolet 3...             5.0
...                                                                             ...
zxcsdfd          Clorox Disinfecting Wipes Value Pack Scented 15...             5.0
zxjki            Clorox Disinfecting Wipes Value Pack Scented 15...             2.0
zyiah4           Clorox Disinfecting Wipes Value Pack Scented 15...             5.0
zzdiane          My Big Fat Greek Wedding 2 (blu-Ray + Dvd + Dig...             5.0
zzz1127          Clorox Disinfecting Wipes Value Pack Scented 15...             4.0

[27588 rows x 1 columns]

In [ ]:
df_master =  df_master.groupby(by=["reviews_username","name"]).mean().reset_index()

In [40]:
df_master.shape

(27588, 3)

## Dividing the dataset into train and test

In [35]:
# Test and Train split of the dataset.
from sklearn.model_selection import train_test_split
train, test = train_test_split(df_master, test_size=0.30, random_state=31)

In [36]:
print(train.shape)
print(test.shape)

(19311, 3)
(8277, 3)


In [52]:
train['reviews_username'].nunique()

17868

In [41]:
df_pivot = train.pivot(
    index='reviews_username',
    columns='name',
    values='reviews_rating'
).fillna(0)

df_pivot.head(3)

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  ...  Yes To Grapefruit Rejuvenating Body Wash
reviews_username                                                                 ...                                          
00dog3                                                          0.0              ...                                       0.0
00sab00                                                         0.0              ...                                       0.0
01impala                                                        0.0              ...                                       0.0

[3 rows x 256 columns]

In [42]:
df_pivot.shape

(17868, 256)

### Creating dummy train & dummy test dataset
These dataset will be used for prediction 
- Dummy train will be used later for prediction of the movies which has not been rated by the user. To ignore the movies rated by the user, we will mark it as 0 during prediction. The movies not rated by user is marked as 1 for prediction in dummy train dataset. 

- Dummy test will be used for evaluation. To evaluate, we will only make prediction on the movies rated by the user. So, this is marked as 1. This is just opposite of dummy_train.

In [53]:
# Copy the train dataset into dummy_train
dummy_train = train.copy()

In [54]:
dummy_train.head()

reviews_username  ... reviews_rating
23966      southern123  ...            5.0
20176        pamelarei  ...            5.0
4296            bzmama  ...            5.0
9913        haliesmith  ...            5.0
12553        jokers709  ...            5.0

[5 rows x 3 columns]

In [55]:
# The movies not rated by user is marked as 1 for prediction. 
dummy_train['reviews_rating'] = dummy_train['reviews_rating'].apply(lambda x: 0 if x>=1 else 1)

In [56]:
# Convert the dummy train dataset into matrix format.
dummy_train = dummy_train.pivot(
    index='reviews_username',
    columns='name',
    values='reviews_rating'
).fillna(1)

In [57]:
dummy_train.head()

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  ...  Yes To Grapefruit Rejuvenating Body Wash
reviews_username                                                                 ...                                          
00dog3                                                          1.0              ...                                       1.0
00sab00                                                         1.0              ...                                       1.0
01impala                                                        1.0              ...                                       1.0
02dakota                                                        1.0              ...                                       1.0
02deuce                                                         1.0              ...                                       1.0

[5 rows x 256 columns]

**Cosine Similarity**

Cosine Similarity is a measurement that quantifies the similarity between two vectors [Which is Rating Vector in this case] 

**Adjusted Cosine**

Adjusted cosine similarity is a modified version of vector-based similarity where we incorporate the fact that different users have different ratings schemes. In other words, some users might rate items highly in general, and others might give items lower ratings as a preference. To handle this nature from rating given by user , we subtract average ratings for each user from each user's rating for different movies.



# User Similarity Matrix

## Using Cosine Similarity

In [59]:
df_pivot.index.nunique()

17868

In [60]:
from sklearn.metrics.pairwise import pairwise_distances

# Creating the User Similarity Matrix using pairwise_distance function.
user_correlation = 1 - pairwise_distances(df_pivot, metric='cosine')
user_correlation[np.isnan(user_correlation)] = 0
print(user_correlation)

[[1.        0.        0.        ... 0.        0.        0.       ]
 [0.        1.        0.        ... 0.        0.9486833 0.       ]
 [0.        0.        1.        ... 0.        0.        0.       ]
 ...
 [0.        0.        0.        ... 1.        0.        1.       ]
 [0.        0.9486833 0.        ... 0.        1.        0.       ]
 [0.        0.        0.        ... 1.        0.        1.       ]]


In [61]:
user_correlation.shape

(17868, 17868)

## Using adjusted Cosine 

### Here, we are not removing the NaN values and calculating the mean only for the movies rated by the user

In [62]:
# Create a user-movie matrix.
df_pivot = train.pivot(
    index='reviews_username',
    columns='name',
    values='reviews_rating'
)

In [63]:
df_pivot.head()

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  ...  Yes To Grapefruit Rejuvenating Body Wash
reviews_username                                                                 ...                                          
00dog3                                                          NaN              ...                                       NaN
00sab00                                                         NaN              ...                                       NaN
01impala                                                        NaN              ...                                       NaN
02dakota                                                        NaN              ...                                       NaN
02deuce                                                         NaN              ...                                       NaN

[5 rows x 256 columns]

### Normalising the rating of the movie for each user around 0 mean

In [64]:
mean = np.nanmean(df_pivot, axis=1)
df_subtracted = (df_pivot.T-mean).T

In [65]:
df_subtracted.head()

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  ...  Yes To Grapefruit Rejuvenating Body Wash
reviews_username                                                                 ...                                          
00dog3                                                          NaN              ...                                       NaN
00sab00                                                         NaN              ...                                       NaN
01impala                                                        NaN              ...                                       NaN
02dakota                                                        NaN              ...                                       NaN
02deuce                                                         NaN              ...                                       NaN

[5 rows x 256 columns]

### Finding cosine similarity

In [66]:
from sklearn.metrics.pairwise import pairwise_distances

In [67]:
# Creating the User Similarity Matrix using pairwise_distance function.
user_correlation = 1 - pairwise_distances(df_subtracted.fillna(0), metric='cosine')
user_correlation[np.isnan(user_correlation)] = 0
print(user_correlation)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [68]:
user_correlation.shape

(17868, 17868)

## Prediction - User User

Doing the prediction for the users which are positively related with other users, and not the users which are negatively related as we are interested in the users which are more similar to the current users. So, ignoring the correlation for values less than 0. 

In [69]:
user_correlation[user_correlation<0]=0
user_correlation

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

Rating predicted by the user (for movies rated as well as not rated) is the weighted sum of correlation with the movie rating (as present in the rating dataset). 

In [70]:
user_predicted_ratings = np.dot(user_correlation, df_pivot.fillna(0))
user_predicted_ratings

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 3.03064063, 0.        , ..., 0.77051412, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [71]:
user_predicted_ratings.shape

(17868, 256)

In [72]:
user_predicted_ratings

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 3.03064063, 0.        , ..., 0.77051412, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

Since we are interested only in the movies not rated by the user, we will ignore the movies rated by the user by making it zero. 

In [73]:
user_final_rating = np.multiply(user_predicted_ratings,dummy_train)
user_final_rating.head()

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  ...  Yes To Grapefruit Rejuvenating Body Wash
reviews_username                                                                 ...                                          
00dog3                                                          0.0              ...                                       0.0
00sab00                                                         0.0              ...                                       0.0
01impala                                                        0.0              ...                                       0.0
02dakota                                                        0.0              ...                                       0.0
02deuce                                                         0.0              ...                                       0.0

[5 rows x 256 columns]

### Finding the top 5 recommendation for the *user*

In [91]:
# Take the user ID as input.
user_input = str(input("Enter your user name"))
print(user_input)

Enter your user name123numbers
123numbers


In [92]:
user_final_rating.head(20)

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  ...  Yes To Grapefruit Rejuvenating Body Wash
reviews_username                                                                 ...                                          
00dog3                                                          0.0              ...                                    0.0000
00sab00                                                         0.0              ...                                    0.0000
01impala                                                        0.0              ...                                    0.0000
02dakota                                                        0.0              ...                                    0.0000
02deuce                                                         0.0              ...                                    0.0000
0325home                                                        0.0              ...                                    0.0000
06stidriver                                                     0.0              ...                                    0.0000
09mommy11                                                       0.0              ...                                    0.0000
1085                                                            0.0              ...                                    0.0000
10ten                                                           0.0              ...                                    0.0000
1143mom                                                         0.0              ...                                    0.0000
11677j                                                          0.0              ...                                    0.0000
1234                                                            0.0              ...                                    0.3698
1234561                                                         0.0              ...                                    0.0000
1234567                                                         0.0              ...                                    0.0000
1234asdf                                                        0.0              ...                                    0.0000
123charlie                                                      0.0              ...                                    0.0000
123numbers                                                      0.0              ...                                    0.0000
123soccermom                                                    0.0              ...                                    0.0000
123too                                                          0.0              ...                                    0.0000

[20 rows x 256 columns]

In [95]:
d = user_final_rating.loc[user_input].sort_values(ascending=False)[0:20]
d

name
Yes To Grapefruit Rejuvenating Body Wash                                     0.0
Yes To Carrots Nourishing Body Wash                                          0.0
Heinz Tomato Ketchup, 38oz                                                   0.0
Head & Shoulders Dandruff Shampoo Ocean Lift 2 In 1                          0.0
Head & Shoulders Classic Clean Conditioner                                   0.0
Hawaiian Punch Berry Limeade Blast Juice                                     0.0
Happy Tot Apple and Butternut Squash                                         0.0
Godzilla 3d Includes Digital Copy Ultraviolet 3d/2d Blu-Ray/dvd              0.0
Germ Guardian174 Elite 3-In-1 Pet Pure True Hepa Air Purifier Ac4300bptca    0.0
Gain Original Scent Liquid Fabric Softener 129 Oz                            0.0
Fiskars174 Classic Stick Rotary Cutter (45 Mm)                               0.0
Finish Quantum Dishwasher Detergent, Lemon Sparkle Scent, 45 Count           0.0
Finish Gelpacs Dishwash

In [ ]:
#Mapping with Movie Title / Genres 
movie_mapping = pd.read_csv('https://raw.githubusercontent.com/antrikshsaxena/NLPCapstone/main/movies.csv')
movie_mapping.head()

movieId  ...                                       genres
0        1  ...  Adventure|Animation|Children|Comedy|Fantasy
1        2  ...                   Adventure|Children|Fantasy
2        3  ...                               Comedy|Romance
3        4  ...                         Comedy|Drama|Romance
4        5  ...                                       Comedy

[5 rows x 3 columns]

In [ ]:
d = pd.merge(d,movie_mapping,left_on='movieId',right_on='movieId', how = 'left')
d.head()

movieId  ...                       genres
0      296  ...  Comedy|Crime|Drama|Thriller
1     2571  ...       Action|Sci-Fi|Thriller
2      318  ...                  Crime|Drama
3     2959  ...  Action|Crime|Drama|Thriller
4      593  ...        Crime|Horror|Thriller

[5 rows x 4 columns]

# Evaluation - User User 

Evaluation will we same as you have seen above for the prediction. The only difference being, you will evaluate for the movie already rated by the user insead of predicting it for the movie not rated by the user. 

In [ ]:
# Find out the common users of test and train dataset.
common = test[test.userId.isin(train.userId)]
common.shape

(90038, 4)

In [ ]:
common.head()

userId  movieId  rating   timestamp
29643      226     3156     1.0  1059516139
152649    1074     2194     3.0   906133915
123175     886     4886     3.5  1168350634
23712      185     1101     4.0  1191923488
99726      757      908     3.5  1184016903

In [ ]:
# convert into the user-movie matrix.
common_user_based_matrix = common.pivot_table(index='userId', columns='movieId', values='rating')

In [ ]:
common_user_based_matrix.head()

movieId  1       2       3       4       ...  205499  206499  206805  207309
userId                                   ...                                
1           NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
2           NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
3           4.0     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
4           NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
5           NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN

[5 rows x 9529 columns]

In [ ]:
# Convert the user_correlation matrix into dataframe.
user_correlation_df = pd.DataFrame(user_correlation)

In [ ]:
user_correlation_df.head()

0         1         2     ...      2068     2069      2070
0  1.000000  0.001899  0.016571  ...  0.020284  0.00000  0.004454
1  0.001899  1.000000  0.024391  ...  0.034615  0.00000  0.000000
2  0.016571  0.024391  1.000000  ...  0.112607  0.00000  0.017203
3  0.000000  0.014429  0.062999  ...  0.045028  0.00000  0.004144
4  0.000000  0.009537  0.040416  ...  0.014523  0.03769  0.009734

[5 rows x 2071 columns]

In [ ]:
df_subtracted.head(1)

movieId  1       2       3       4       ...  206861  207309  208002  208793
userId                                   ...                                
1           NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN

[1 rows x 12911 columns]

In [ ]:
# df_subtracted.head()

In [ ]:
user_correlation_df['userId'] = df_subtracted.index

user_correlation_df.set_index('userId',inplace=True)
user_correlation_df.head()

0         1         2     ...      2068     2069      2070
userId                                ...                             
1       1.000000  0.001899  0.016571  ...  0.020284  0.00000  0.004454
2       0.001899  1.000000  0.024391  ...  0.034615  0.00000  0.000000
3       0.016571  0.024391  1.000000  ...  0.112607  0.00000  0.017203
4       0.000000  0.014429  0.062999  ...  0.045028  0.00000  0.004144
5       0.000000  0.009537  0.040416  ...  0.014523  0.03769  0.009734

[5 rows x 2071 columns]

In [ ]:
common.head(1)

userId  movieId  rating   timestamp
29643     226     3156     1.0  1059516139

In [ ]:
list_name = common.userId.tolist()

user_correlation_df.columns = df_subtracted.index.tolist()


user_correlation_df_1 =  user_correlation_df[user_correlation_df.index.isin(list_name)]

In [ ]:
user_correlation_df_1.shape

(2071, 2071)

In [ ]:
user_correlation_df_2 = user_correlation_df_1.T[user_correlation_df_1.T.index.isin(list_name)]

In [ ]:
user_correlation_df_3 = user_correlation_df_2.T

In [ ]:
user_correlation_df_3.head()

1         2         3     ...      2069     2070      2071
userId                                ...                             
1       1.000000  0.001899  0.016571  ...  0.020284  0.00000  0.004454
2       0.001899  1.000000  0.024391  ...  0.034615  0.00000  0.000000
3       0.016571  0.024391  1.000000  ...  0.112607  0.00000  0.017203
4       0.000000  0.014429  0.062999  ...  0.045028  0.00000  0.004144
5       0.000000  0.009537  0.040416  ...  0.014523  0.03769  0.009734

[5 rows x 2071 columns]

In [ ]:
user_correlation_df_3.shape

(2071, 2071)

In [ ]:
user_correlation_df_3[user_correlation_df_3<0]=0

common_user_predicted_ratings = np.dot(user_correlation_df_3, common_user_based_matrix.fillna(0))
common_user_predicted_ratings

array([[5.10460224e+00, 1.74539764e+00, 6.96831596e-01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.02224987e+01, 6.74419414e+00, 2.26162307e+00, ...,
        1.99325288e-01, 0.00000000e+00, 0.00000000e+00],
       [3.57707385e+01, 1.15467646e+01, 2.97886475e+00, ...,
        4.02202154e-01, 1.42784707e-01, 1.42784707e-01],
       ...,
       [3.42388737e+01, 1.00466459e+01, 4.12806648e+00, ...,
        2.66442361e-01, 3.56811942e-02, 3.56811942e-02],
       [3.66282688e+00, 1.23265539e+00, 1.14883522e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.83078030e+01, 7.19569850e+00, 2.61970557e+00, ...,
        6.05070641e-02, 7.60002285e-02, 7.60002285e-02]])

In [ ]:
dummy_test = common.copy()

dummy_test['rating'] = dummy_test['rating'].apply(lambda x: 1 if x>=1 else 0)

dummy_test = dummy_test.pivot_table(index='userId', columns='movieId', values='rating').fillna(0)

In [ ]:
dummy_test.shape

(2071, 9529)

In [ ]:
common_user_based_matrix.head()

movieId  1       2       3       4       ...  205499  206499  206805  207309
userId                                   ...                                
1           NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
2           NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
3           4.0     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
4           NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
5           NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN

[5 rows x 9529 columns]

In [ ]:
dummy_test.head()

movieId  1       2       3       4       ...  205499  206499  206805  207309
userId                                   ...                                
1           0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
2           0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
3           1.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
4           0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
5           0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0

[5 rows x 9529 columns]

In [ ]:
common_user_predicted_ratings = np.multiply(common_user_predicted_ratings,dummy_test)

In [ ]:
common_user_predicted_ratings.head()

movieId     1       2       3       4       ...  205499  206499  206805  207309
userId                                      ...                                
1         0.000000     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
2         0.000000     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
3        35.770738     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
4         0.000000     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
5         0.000000     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0

[5 rows x 9529 columns]

Calculating the RMSE for only the movies rated by user. For RMSE, normalising the rating to (1,5) range.

In [ ]:
from sklearn.preprocessing import MinMaxScaler
from numpy import *

X  = common_user_predicted_ratings.copy() 
X = X[X>0]

scaler = MinMaxScaler(feature_range=(1, 5))
print(scaler.fit(X))
y = (scaler.transform(X))

print(y)

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_data.py:375: RuntimeWarning: All-NaN slice encountered
  data_min = np.nanmin(X, axis=0)
/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_data.py:376: RuntimeWarning: All-NaN slice encountered
  data_max = np.nanmax(X, axis=0)


MinMaxScaler(copy=True, feature_range=(1, 5))
[[     nan      nan      nan ...      nan      nan      nan]
 [     nan      nan      nan ...      nan      nan      nan]
 [3.563153      nan      nan ...      nan      nan      nan]
 ...
 [     nan      nan      nan ...      nan      nan      nan]
 [     nan      nan      nan ...      nan      nan      nan]
 [     nan      nan      nan ...      nan      nan      nan]]


In [ ]:
common_ = common.pivot_table(index='userId', columns='movieId', values='rating')

In [ ]:
# Finding total non-NaN value
total_non_nan = np.count_nonzero(~np.isnan(y))

In [ ]:
rmse = (sum(sum((common_ - y )**2))/total_non_nan)**0.5
print(rmse)

1.4350750583833054


## Using Item similarity

# Item Based Similarity

Taking the transpose of the rating matrix to normalize the rating around the mean for different movie ID. In the user based similarity, we had taken mean for each user instead of each movie. 

In [96]:
df_pivot = train.pivot(
    index='reviews_username',
    columns='name',
    values='reviews_rating'
).T

df_pivot.head()

reviews_username                                    00dog3  ...  zzz1127
name                                                        ...         
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...     NaN  ...      NaN
100:Complete First Season (blu-Ray)                    NaN  ...      NaN
2017-2018 Brownline174 Duraflex 14-Month Planne...     NaN  ...      NaN
2x Ultra Era with Oxi Booster, 50fl oz                 NaN  ...      NaN
42 Dual Drop Leaf Table with 2 Madrid Chairs"          NaN  ...      NaN

[5 rows x 17868 columns]

Normalising the movie rating for each movie for using the Adujsted Cosine

In [97]:
mean = np.nanmean(df_pivot, axis=1)
df_subtracted = (df_pivot.T-mean).T

In [98]:
df_subtracted.head()

reviews_username                                    00dog3  ...  zzz1127
name                                                        ...         
0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. F...     NaN  ...      NaN
100:Complete First Season (blu-Ray)                    NaN  ...      NaN
2017-2018 Brownline174 Duraflex 14-Month Planne...     NaN  ...      NaN
2x Ultra Era with Oxi Booster, 50fl oz                 NaN  ...      NaN
42 Dual Drop Leaf Table with 2 Madrid Chairs"          NaN  ...      NaN

[5 rows x 17868 columns]

Finding the cosine similarity using pairwise distances approach

In [99]:
from sklearn.metrics.pairwise import pairwise_distances

In [100]:
# Item Similarity Matrix
item_correlation = 1 - pairwise_distances(df_subtracted.fillna(0), metric='cosine')
item_correlation[np.isnan(item_correlation)] = 0
print(item_correlation)

[[ 1.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          1.          0.         ... -0.00512307  0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 ...
 [ 0.         -0.00512307  0.         ...  1.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          1.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   1.        ]]


In [101]:
item_correlation.shape

(256, 256)

Filtering the correlation only for which the value is greater than 0. (Positively correlated)

In [102]:
item_correlation[item_correlation<0]=0
item_correlation

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

# Prediction - Item Item

In [103]:
item_predicted_ratings = np.dot((df_pivot.fillna(0).T),item_correlation)
item_predicted_ratings

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.00084707, 0.        , ..., 0.00211006, 0.        ,
        0.        ],
       [0.        , 0.015696  , 0.        , ..., 0.        , 0.        ,
        0.01186601],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [104]:
item_predicted_ratings.shape

(17868, 256)

In [105]:
dummy_train.shape

(17868, 256)

### Filtering the rating only for the movies not rated by the user for recommendation

In [106]:
item_final_rating = np.multiply(item_predicted_ratings,dummy_train)
item_final_rating.head()

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  ...  Yes To Grapefruit Rejuvenating Body Wash
reviews_username                                                                 ...                                          
00dog3                                                          0.0              ...                                  0.000000
00sab00                                                         0.0              ...                                  0.000000
01impala                                                        0.0              ...                                  0.011866
02dakota                                                        0.0              ...                                  0.019777
02deuce                                                         0.0              ...                                  0.015821

[5 rows x 256 columns]

### Finding the top 5 recommendation for the *user*



In [112]:
# Take the user ID as input
user_input = str(input("Enter your user name"))
print(user_input)

Enter your user name1234567
1234567


In [111]:
item_final_rating.head(20)

name              0.6 Cu. Ft. Letter A4 Size Waterproof 30 Min. Fire File Chest  ...  Yes To Grapefruit Rejuvenating Body Wash
reviews_username                                                                 ...                                          
00dog3                                                          0.0              ...                                  0.000000
00sab00                                                         0.0              ...                                  0.000000
01impala                                                        0.0              ...                                  0.011866
02dakota                                                        0.0              ...                                  0.019777
02deuce                                                         0.0              ...                                  0.015821
0325home                                                        0.0              ...                                  0.000000
06stidriver                                                     0.0              ...                                  0.000000
09mommy11                                                       0.0              ...                                  0.000000
1085                                                            0.0              ...                                  0.000000
10ten                                                           0.0              ...                                  0.000000
1143mom                                                         0.0              ...                                  0.000000
11677j                                                          0.0              ...                                  0.000000
1234                                                            0.0              ...                                  0.015821
1234561                                                         0.0              ...                                  0.000000
1234567                                                         0.0              ...                                  0.000000
1234asdf                                                        0.0              ...                                  0.000000
123charlie                                                      0.0              ...                                  0.015821
123numbers                                                      0.0              ...                                  0.019777
123soccermom                                                    0.0              ...                                  0.000000
123too                                                          0.0              ...                                  0.000000

[20 rows x 256 columns]

In [113]:
# Recommending the Top 5 products to the user.
d = item_final_rating.loc[user_input].sort_values(ascending=False)[0:20]
d

name
Clorox Disinfecting Bathroom Cleaner                                              0.600598
Mrs. Meyer's174 Lemon Verbena Laundry Scent Booster - 18oz                        0.025718
L'or233al Paris Elvive Extraordinary Clay Rebalancing Conditioner - 12.6 Fl Oz    0.025338
Nature's Path Chunky Chocolate Peanut Chewy Granola Bars                          0.019733
Nexxus Exxtra Gel Style Creation Sculptor                                         0.015771
Chips Deluxe Soft 'n Chewy Cookies                                                0.011393
Planes: Fire Rescue (2 Discs) (includes Digital Copy) (blu-Ray/dvd)               0.010572
Stander Pt Bedcane - Bed Handle                                                   0.010190
Dark Shadows (includes Digital Copy) (ultraviolet) (dvdvideo)                     0.009371
Kind Nut Delight Bar                                                              0.008056
Musselman Apple Sauce, Cinnamon, 48oz                                             0.0

In [ ]:
#Mapping with Movie Title / Genres 
movie_mapping = pd.read_csv('https://raw.githubusercontent.com/antrikshsaxena/NLPCapstone/main/movies.csv', encoding='latin-1')

In [ ]:
d = pd.merge(d,movie_mapping,left_on='movieId',right_on='movieId',how = 'left')
d.head()

movieId  ...                genres
0    27834  ...                 Drama
1     7637  ...          Comedy|Drama
2     3559  ...  Comedy|Drama|Romance
3     5269  ...                 Drama
4     6440  ...        Drama|Thriller

[5 rows x 4 columns]

In [ ]:
train_new = pd.merge(train,movie_mapping,left_on='movieId',right_on='movieId',how='left')
train_new[train_new.userId == 1] .head()

userId  ...                    genres
2866        1  ...            Drama|Thriller
4548        1  ...                     Drama
11584       1  ...             Drama|Romance
13280       1  ...             Drama|Romance
17280       1  ...  Crime|Film-Noir|Thriller

[5 rows x 6 columns]

# Evaluation - Item Item

Evaluation will we same as you have seen above for the prediction. The only difference being, you will evaluate for the movie already rated by the user insead of predicting it for the movie not rated by the user. 

In [ ]:
test.columns

Index(['userId', 'movieId', 'rating', 'timestamp'], dtype='object')

In [ ]:
common =  test[test.movieId.isin(train.movieId)]
common.shape

(88035, 4)

In [ ]:
common.head(4)

userId  movieId  rating   timestamp
29643      226     3156     1.0  1059516139
152649    1074     2194     3.0   906133915
123175     886     4886     3.5  1168350634
23712      185     1101     4.0  1191923488

In [ ]:
common_item_based_matrix = common.pivot_table(index='userId', columns='movieId', values='rating').T

In [ ]:
common_item_based_matrix.shape

(7783, 2071)

In [ ]:
item_correlation_df = pd.DataFrame(item_correlation)

In [ ]:
item_correlation_df.head(1)

0         1      2        3         4      ...  12906  12907  12908  12909  12910
0    1.0  0.102915    0.0  0.00434  0.095113  ...    0.0    0.0    0.0    0.0    0.0

[1 rows x 12911 columns]

In [ ]:
item_correlation_df['movieId'] = df_subtracted.index
item_correlation_df.set_index('movieId',inplace=True)
item_correlation_df.head()

0         1         2         3      ...  12907  12908  12909  12910
movieId                                          ...                            
1        1.000000  0.102915  0.000000  0.004340  ...    0.0    0.0    0.0    0.0
2        0.102915  1.000000  0.031700  0.000000  ...    0.0    0.0    0.0    0.0
3        0.000000  0.031700  1.000000  0.004382  ...    0.0    0.0    0.0    0.0
4        0.004340  0.000000  0.004382  1.000000  ...    0.0    0.0    0.0    0.0
5        0.095113  0.060859  0.069432  0.038519  ...    0.0    0.0    0.0    0.0

[5 rows x 12911 columns]

In [ ]:
list_name = common.movieId.tolist()

In [ ]:
item_correlation_df.columns = df_subtracted.index.tolist()

item_correlation_df_1 =  item_correlation_df[item_correlation_df.index.isin(list_name)]

In [ ]:
item_correlation_df_2 = item_correlation_df_1.T[item_correlation_df_1.T.index.isin(list_name)]

item_correlation_df_3 = item_correlation_df_2.T

In [ ]:
item_correlation_df_3.head()

1         2         3       ...   205383  206499  207309
movieId                                ...                         
1        1.000000  0.102915  0.000000  ...  0.00000     0.0     0.0
2        0.102915  1.000000  0.031700  ...  0.10963     0.0     0.0
3        0.000000  0.031700  1.000000  ...  0.00000     0.0     0.0
4        0.004340  0.000000  0.004382  ...  0.00000     0.0     0.0
5        0.095113  0.060859  0.069432  ...  0.00000     0.0     0.0

[5 rows x 7783 columns]

In [ ]:
item_correlation_df_3[item_correlation_df_3<0]=0

common_item_predicted_ratings = np.dot(item_correlation_df_3, common_item_based_matrix.fillna(0))
common_item_predicted_ratings


array([[ 1.10153262, 12.83252349, 35.8647666 , ...,  9.1484491 ,
         0.51093827,  9.15792271],
       [ 0.39077366,  9.74879386, 22.62663044, ...,  7.05031014,
         0.92552995,  6.28294116],
       [ 0.11700293,  4.30626816,  8.2908921 , ...,  3.77831808,
         0.26364204,  3.77408128],
       ...,
       [ 0.43354838,  3.97316391, 22.48683777, ...,  6.770097  ,
         0.1689317 ,  4.1952958 ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [ ]:
common_item_predicted_ratings.shape

(7783, 2071)

Dummy test will be used for evaluation. To evaluate, we will only make prediction on the movies rated by the user. So, this is marked as 1. This is just opposite of dummy_train



In [ ]:
dummy_test = common.copy()

dummy_test['rating'] = dummy_test['rating'].apply(lambda x: 1 if x>=1 else 0)

dummy_test = dummy_test.pivot_table(index='userId', columns='movieId', values='rating').T.fillna(0)

common_item_predicted_ratings = np.multiply(common_item_predicted_ratings,dummy_test)

The products not rated is marked as 0 for evaluation. And make the item- item matrix representaion.


In [ ]:
common_ = common.pivot_table(index='userId', columns='movieId', values='rating').T

In [ ]:
from sklearn.preprocessing import MinMaxScaler
from numpy import *

X  = common_item_predicted_ratings.copy() 
X = X[X>0]

scaler = MinMaxScaler(feature_range=(1, 5))
print(scaler.fit(X))
y = (scaler.transform(X))

print(y)

MinMaxScaler(copy=True, feature_range=(1, 5))
[[       nan        nan 2.52545034 ...        nan        nan        nan]
 [       nan        nan        nan ...        nan        nan        nan]
 [       nan        nan        nan ...        nan        nan        nan]
 ...
 [       nan        nan        nan ...        nan        nan        nan]
 [       nan        nan        nan ...        nan        nan        nan]
 [       nan        nan        nan ...        nan        nan        nan]]


In [ ]:
# Finding total non-NaN value
total_non_nan = np.count_nonzero(~np.isnan(y))

In [ ]:
rmse = (sum(sum((common_ - y )**2))/total_non_nan)**0.5
print(rmse)

1.3169197240439345


##**Summary - Recommendation Engine**